quick update to exposure (edits from Pragya)
chime-frb-open-data/chime-frb-open-data.github.io pull request #6
Opened 2021-06-09 17:23 UTC by sabrinastronomy

2021-06-09 16:08 UTC, shinybrar commented
@brandon-feder With the release of v2021.6.2 `cfod` now supports python 3.7+

2021-06-09 19:33 UTC, shinybrar requested changes
Please remove .idea folder from this PR

2021-06-09 19:54 UTC, sabrinastronomy commented
@shinybrar , .idea folder has been removed

2021-06-10 16:31 UTC, shinybrar approved these changes
LGTM.

2021-06-10 16:31 UTC, merged